@startuml

participant Navigateur
participant Vue

Navigateur -> Controleur : POST /ajouterMembreCanal\nidPersonne,idCanal
Controleur -> Controleur : verifie droit de faire l'operation
Controleur -> Controleur : verifie idPersonne et idCanal entiers
Controleur -> Dao: CanalDao.\najouterMembreAuCanal(idMembre, idCanal) 
Dao -> SGBD: INSERT INTO \n membreCanal ...
SGBD -> Dao: true or sql exception
Dao -> Controleur: true or sql exception
== Si ok ==
Controleur -> Navigateur: redirect vers membresCanal?idCanal=...
== Si pb (doublon par exemple) ==
Controleur -> Vue: membresCanal.jsp
Vue -> Navigateur: liste des membres\navec message d'erreur
@enduml