@startuml 
participant Navigateur 
participant Vue  
Navigateur -> Controleur : GET /canaux 
Controleur -> Controleur : recuperee le idPersonne\ndu user en session
Controleur -> Dao: CanalDao.getAllByIdPersonne(idPersonne)
Dao -> SGBD: SELECT *\nFROM canal WHERE...
SGBD -> Dao : canaux trouvés
Dao -> Controleur: List<Canal> 
Controleur -> Vue: canaux.jsp 
Vue -> Navigateur: tableau des canaux
@enduml