@startuml 
participant Navigateur 
participant Vue  
Navigateur -> Controleur : GET /canaux 
Controleur -> Dao: CanalDao.getAllCanaux()
Dao -> SGBD: SELECT *\nFROM canal
SGBD -> Dao : canaux trouvés
Dao -> Controleur: List<Canal> 
Controleur -> Vue: canaux.jsp 
Vue -> Navigateur: tableau des canaux
@enduml