@startuml
participant Navigateur
participant Vue
Navigateur -> Controleur : GET /membresCanal?idCanal=...
Controleur -> Controleur : verifie aue idCanal est entier
Controleur -> Dao : CanalDao.getMembreByIdCanal(idCanal)
Dao -> SGBD : SELECT * from membre_canal WHERE ...
SGBD -> Dao : n lignes
Dao -> Controleur : List<Personne>
Controleur -> Vue : membresCanal.jsp
Vue -> Navigateur : liste en tableau,\navec formulaire pour\najouter un membre\net un bouton de suppression\nface a chaque membre

@enduml
