@startuml
participant Navigateur
participant Vue
Navigateur -> Controller : GET/{nom_canal}\nMembreController.ListAll()
Controller -> Service : MembreService\n.listAll()
Service -> Repository : MembreRepository.findAll()
Repository -> Service : Iterable<Membre>
Service -> Controller : membres = List<Membre>
Controller -> Vue : ModelAndViex\n("membres", membres)
Vue -> Navigateur : /{nom_canal}/membres
@enduml