@startuml
participant Navigateur
participant Vue
Navigateur -> Controller : GET/canaux\nCanalController\n.canauxById(idPersonne)
Controller -> Service : CanalService\n.listCanauxById(idPersonne)
Service -> Repository : CanalRepository\n.findCanauxById(idPersonne)
Repository -> Service : Iterable<Canal>
Service -> Controller : canaux = List<Canal>
Controler -> Vue : ModelAndViex\n("canaux", canaux)
Vue -> Navigateur : /canaux
@enduml