@startuml
participant Navigateur
participant Vue
Navigateur -> Controller : GET/canaux/{id_canal}\nPersonneController.listMembre(int idCanal)
Controller -> Service : PersonneService\n.listMembreByCanal(int idCanal)
Service -> Repository : PersonneRepository\n.findMembreByCanal(int idCanal)
Repository -> Service : Collection<Personne>
Service -> Controller : Collection<Personne>
Controller -> Vue : ModelAndView\n("membres", Collection<Personne>)
Vue -> Navigateur : /canaux/{nom_canal}
@enduml