DROP SCHEMA IF EXISTS cdamassy2021 ;

CREATE SCHEMA IF NOT EXISTS cdamassy2021 DEFAULT CHARACTER SET utf8 ;
USE cdamassy2021 ;

CREATE TABLE IF NOT EXISTS personne (
  id_personne INT(11) NOT NULL AUTO_INCREMENT,
  prenom VARCHAR(45) NOT NULL,
  nom VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  pwd VARCHAR(45) NOT NULL,
  tel VARCHAR(45) NOT NULL,
  est_formateur TINYINT NOT NULL DEFAULT 0,
  est_gestionnaire VARCHAR(45) NOT NULL DEFAULT 0,
  est_administrateur VARCHAR(45) NOT NULL DEFAULT 0,
  url_photo VARCHAR(65) NULL,
  token VARCHAR(255) NULL,
  inscrit_a VARCHAR(45) NULL,
  PRIMARY KEY (id_personne),
  UNIQUE INDEX email_UNIQUE (email ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

